databases:
  - name: inventory-management-db
    databaseName: inventory_management
    user: inventory_user
    plan: free

services:
  - type: web
    name: inventory-management-system
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn app.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: inventory_management.settings
      - key: DEBUG
        value: False
      - key: DB_NAME
        fromDatabase:
          name: inventory-management-db
          property: databaseName
      - key: DB_USER
        fromDatabase:
          name: inventory-management-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: inventory-management-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: inventory-management-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: inventory-management-db
          property: port